# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
#
#   All parameters avaliable to each menu item
#  [[main]]
#   id = "" # important if name is left blank
#   name = "" # title displayed is {{ .Pre }}{{ .Name }}{{ .Post }}
#   pre = "" # intented to add HTML like icons. Leave blank if no extra HTML is needed.
#   post = "" # intented to add HTML like icons. Leave blank if no extra HTML is needed.
#   url = "" # Link URL.
#   weight = 10 # Defines the order the menu items are displayed.
#   [main.params]
#    tooltip = "" # Add tooltip to menu item. Not supported for dropdown items.
#    tooltip_placement = "" # Tooltip placement. Pick top, bottom, left or right. Defaults to bottom.
#
#   Use [[main_right]] to add right jusified menu items when standard items are left jusified.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 40

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/cv.pdf"
#    weight = 70
